### ISSUE TITLE
Deleting a new item will delete all new items

### ISSUE THREAD

**Issue by abadi199** [jschomay/elm-paginate#3]
Thanks for creating this package, I've been wanting to write a reusable paging library for elm, now I don't have to anymore 😄 

Btw, I found a small bug in the demo app. Here's to reproduce the issue:
- Add a couple of new items.
- Delete one new item, it will remove all the new item.

**Comment by abadi199** [comment]
Ah, after looking at the code, I think it's because new items are all just the same text of "new item". So maybe this is not really a bug, but a design decision to keep thing simple?

**Comment by MorganEarlJones** [comment]
This appears to be because the DeleteItem case of src/Example.elm's update function deletes items by filtering against the contents of the string, which means that all items named "new item" get tossed.

DeleteItem item ->
    let removeItem =
        List.filter ((/=) item)
    in
        { model | things = Paginate.map removeItem model.things }

Perhaps this could be remedied by indexing the list items in tuples with Integers and filtering against that instead?

**Comment by jschomay** [comment]
Hi @abadi199, nice to hear from you!  I am aware of this "bug."  It's annoying, but I chose to leave it as is to keep the example simple as you suggested.  I thought about using an indexed map as @MorganEarlJones  suggested, but if you add a new item, then delete an older item, then add an item again it would duplicate the id still, in an even more confusing way.  A solution would be to add some kind of global id generator, but as that has nothing to do with pagination, I thought it would just add noise and confusion, so I left it as is.

Real apps would have a better way to identify items in their domain, so this "bug" is only an issue in my toy example.  I was wondering if people would run into it, I guess so!  Hopefully it's not too confusing, if it is I can add a global id.

**Comment by jschomay** [comment]
What the heck, I went ahead and fixed it, it's a pretty simple change and this will avoid any confusion for others.  (92d60a0).

Thanks.
