### ISSUE TITLE
0.19 Support?

### ISSUE THREAD

**Issue by thorebear** [jschomay/elm-paginate#7]
Will elm-paginate be published for Elm 0.19?

**Comment by jschomay** [comment]
Hi @thorebear.  I knew this request was coming!  I do plan on updating elm-paginate to Elm 0.19.  I am not sure when I will be able to do that, but I will try to do so as soon as I can.

**Comment by jschomay** [comment]
Updated!  Both elm-paginate and elm-bounded-number (which elm-paginate depends on) have been updated to 0.19.  Let me know if there are any issues you encounter.
