### ISSUE TITLE
Docs still use 0.18 syntax

### ISSUE THREAD

**Issue by stevensonmt** [jschomay/elm-paginate#9]
If anything substantive changed in the migration to 0.19, you might need to update the documentation. Currently it uses the `Html.program` syntax instead of the `Browser.element` used in 0.19.

**Comment by jschomay** [comment]
Good catch, thanks.  I assume you are only referring to the readme?

Fixed in tag `3.1.1` - https://package.elm-lang.org/packages/jschomay/elm-paginate/3.1.1/

**Comment by stevensonmt** [comment]
Yes, that's what I was referring to. Thanks for updating.
